name: vms

networks:
  vms-network:

services:  
  vms-backend:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      .env
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - vms-network
    depends_on:
      vms-db:
        condition: service_healthy

  vms-db:
      image: postgres:latest
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d vms"]
        interval: 30s
        timeout: 30s
        retries: 5
      networks:
        - vms-network

volumes:
    postgres_data:
