"""Add user_id column to client table

Revision ID: 5c18b26b0b5f
Revises: 
Create Date: 2025-07-04 04:52:52.749519

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c18b26b0b5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('user_id',
                                      sqlmodel.sql.sqltypes.AutoString(), nullable=False))  # noqa: F821
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'user_id')
    # ### end Alembic commands ###
