"""Add User table

Revision ID: a9ba6788a8e9
Revises: 5c18b26b0b5f
Create Date: 2025-07-04 17:06:04.829065

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a9ba6788a8e9'
down_revision: Union[str, Sequence[str], None] = '5c18b26b0b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['id'])
    op.create_unique_constraint(None, 'client', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
